# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.11.0'
pod 'Fabric', '~> 1.7.13'
pod 'Crashlytics', '~> 3.10.7'
pod 'GoogleAppMeasurement', '5.3'

target 'boscoin_wallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for boscoin_wallet
  target 'boscoin_walletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

